AllCops:
  NewCops: enable
  TargetRubyVersion: 3

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 1

Naming/VariableNumber:
  EnforcedStyle: snake_case

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Max: 80

Style/Documentation:
  Enabled: false
